### ISSUE TITLE
Not change on files for parameter calibration

### ISSUE THREAD

**Issue by natiguvi** [chrisschuerz/SWATrunR#39]
Hi Chriss, I hope you'r well

I'm writing because i'm doing a calibration for a large basin,  I already finished flow calibration and now I want to do sediment calibration, but I've noticed that files used for flow calibration for example ".hru", doesn't change values for sediment parameters, using the last thread saved. How can I solved that? I really appreciate your answer. 

Kind regards, 

Nathaly G.

**Comment by chrisschuerz** [comment]
Hi,

I think I need some more info to help you with that. Is your model setup SWAT2012 or SWAT+ (I assume 2012)?  Which parameters did you try to change? In SWAT2012 .hru files you should actually be able to change all parameter that are in there. Could you maybe share some code how you wrote the parameter definition?

Best
Christoph

**Comment by natiguvi** [comment]
Hi, sorry I was tired and forgot to give you more information. This is the code I'm using to define parameters for sce calibration: 

par_names <- c( "CH_K2.rte | change = absval | sub == (149,100,101,102,103,104,111,114,115,120,121,123,124,125,129,130,131,132,133,135,138,139,140,141,143,144,145,146,147,148,150)",
  "CH_COV1.rte | change = absval| sub == (149,100,101,102,103,104,111,114,115,120,121,123,124,125,129,130,131,132,133,135,138,139,140,141,143,144,145,146,147,148,150)",
  "CH_COV2.rte | change = absval | sub == (149,100,101,102,103,104,111,114,115,120,121,123,124,125,129,130,131,132,133,135,138,139,140,141,143,144,145,146,147,148,150)",
  "USLE_P.mgt | change = absval | sub == (149,100,101,102,103,104,111,114,115,120,121,123,124,125,129,130,131,132,133,135,138,139,140,141,143,144,145,146,147,148,150)",
  "LAT_SED.hru | change = absval | sub == (149,100,101,102,103,104,111,114,115,120,121,123,124,125,129,130,131,132,133,135,138,139,140,141,143,144,145,146,147,148,150)",
  "SPEXP.rte | change = absval| sub == (149,100,101,102,103,104,111,114,115,120,121,123,124,125,129,130,131,132,133,135,138,139,140,141,143,144,145,146,147,148,150)",
  "SPCON.rte| change = absval| sub == (149,100,101,102,103,104,111,114,115,120,121,123,124,125,129,130,131,132,133,135,138,139,140,141,143,144,145,146,147,148,150)",
  "PRF.rte| change = absval| sub == (149,100,101,102,103,104,111,114,115,120,121,123,124,125,129,130,131,132,133,135,138,139,140,141,143,144,145,146,147,148,150)",
  "USLE_K().sol | change = pctchg| sub == (149,100,101,102,103,104,111,114,115,120,121,123,124,125,129,130,131,132,133,135,138,139,140,141,143,144,145,146,147,148,150)"
   )  
  
par_init <- c(-0.01,-0.05,-0.001,0,   0,  1,0.0001,0,-70)
par_lwr  <- c(-0.01,-0.05,-0.001,0,   0,  1,0.0001,0,-70)
par_upr  <- c(  0.5,  0.6,     1,1,5000,1.5,  0.01,2, 70)

names(par_init) <- par_names 
names(par_lwr) <- par_names
names(par_upr) <- par_names

I'm changing only that subs because i'm doing a block calibration, but I noticed that for example the .rte files don't change for sediment calibration because I already used it to calibrate cn2 for flow. So, the files that are in the format i'm attaching don't change, i'm assuming that is because don't have the original SWAT2012 format. 

Thank you in advance, best regards
[001040000_rte.txt](https://github.com/chrisschuerz/SWATplusR/files/6946723/001040000_rte.txt)

**Comment by natiguvi** [comment]
I'm also sending you by mail the textinout folder and the R code i'm using if you can please take a look on it.

**Comment by natiguvi** [comment]
Calibr_Flores_Q.zip
<https://drive.google.com/file/d/1Cd14WaFQpCpB50omyzc4tVvzuvIz3BLg/view?usp=drive_web>
Hi Christoph!

Thank you for your quick response, I already responded in the github thread
but it doesn't let me attach the zip txtinout folder and the R code, so I'm
sending it by this way, I hope you can help me with this issue and sorry
for bothering you. Thank you in advance,

Kind regards
Nathaly G.
