### ISSUE TITLE
Error when changing parameters SWAT 2012

### ISSUE THREAD

**Issue by etgay** [chrisschuerz/SWATrunR#65]
Hello,

I have successfully used run_swat2012 to run one of my uncalibrated swat models using the following code: 

sim_uncalib <- run_swat2012(project_path = path, output = out_def)

here is how I defined out_def:
out_def <- list(flow = define_output(file = "rch",
                                     variable = "FLOW_OUT",
                                     unit = 203),
                sed_in  = define_output(file = "rch",
                                     variable = "SED_IN",
                                     unit = 203),
                sed_out = define_output(file = "rch",
                                     variable = "SED_OUT",
                                     unit = 203))

However, when I try to change parameters using a calibrated set I achieved in SWAT-CUP, I receive the following error message: 
Simulation 1 of 1   Time elapsed: 2S   Time remaining: 0S    Error in { : 
  task 1 failed - "Can't recycle `.x` (size 28) to match `.y` (size 27)."

Has anyone received this message? I have tried troubleshooting and searching on the web but can't seem to get the run to work. 
Here is the code I used for the parameter change run:

par_flo <- c("CN2.mgt | change = relchg" = 0.3175,
             "SOL_AWC(1).sol | change = relchg" = -0.001875,
             "OV_N.hru | change = relchg" = 0.09875,
             "SOL_K(1).sol | change = relchg" = 0.063,
             "ALPHA_BF.gw | change = absval" = 0.83725,
             "GW_DELAY.gw | change = absval" = 144.375,
             "GW_REVAP.gw | change = absval" = 0.151975,
             "GWQMN.gw | change = absval" = 236.25,
             "SLSUBBSN.hru | change = absval" = 73.224998,
             "ESCO.hru | change = absval" = 0.41,
             "CH_N2.rte | change = absval" = 0.140775,
             "REVAPMN.gw | change = absval" = 145.73,
             "CH_k2.rte | change = absval" = 279.0925,
             "SURLAG.bsn | change = absval" = 12)

sim_flow_calib <- run_swat2012(project_path = path, 
             output = out_def,
             parameter = par_flo)

**Comment by chrisschuerz** [comment]
@etgay hey sorry for this really late reply, it took me a while now to get back to the R package. I do not know if this question is still relevant to you. The lengths of the vectors that did not match can be when output variables and/or the date vector are different in length. It looks to me as if you wanted to get yearly or monthly outputs, where the issue occured. If this is still relevant to you I can have a look into it. Otherwise just sorry for the late reply.
