### ISSUE TITLE
Error in { : task 2827 failed - "cannot open the connection"

### ISSUE THREAD

**Issue by EhsanBaninajar** [chrisschuerz/SWATrunR#67]
Hi Chris, Thank you for the very useful package. I want to run the model with 5000 simulations. The threads are initiated without a problem and it also do the simulations in parallel without problem. However when the last simulation is finished, instead of saving the information in a variable, I get this error: Error in { : task 2827 failed - "cannot open the connection"
Any idea how to fix this?

This is my code:
q_sim <- run_swat2012(project_path = pathIlam,
                      output = list(q_discharge = define_output(file = "rch",
                                                variable = "FLOW_OUT",
                                                unit = 31),
                      q_ET = define_output(file = "hru",
                                             variable = "ET",
                                             unit = 10)),
                      parameter = par_lhs,
                      start_date = "1997-01-01",
                      end_date = "2016-12-31",
                      years_skip = 3,
                      n_thread = 6)

**Comment by chrisschuerz** [comment]
@EhsanBaninajar does this error always occur, or did you try it only once? The error message alone does not really tell me where the error occured. Can you maybe try to do a few quick runs to see if this was a one time issue or it always happens. You can do that e.g. by only running 12 simulations when you add the argument `run_index = 1:12`.
