### ISSUE TITLE
No simulation output with modified executable

### ISSUE THREAD

**Issue by jmule88** [chrisschuerz/SWATrunR#80]
Hi Chris,

Thanks so much for this straightforward tool for SWAT calibration!

My team has made modifications to the SWAT source code (both to algorithms and also what variables print in the output files). When I run SWATrunR with my modified executable there are no errors, but there is nothing in the "simultation" output. However, when I run SWATrunR with the generic executable from the SWAT website, I successfully get "simulation" outputs. Do you have any advice for how to use SWATrunR with a modified executable?

Thanks for your help!
Jaya

**Comment by chrisschuerz** [comment]
Hey,

it depends on how the model outputs are written with your modified version. If the outputs are still written into the same output files as with the generic exe outputs should be returned correctly. If your exe writes different output files then `run_swat` will look for the wrong files. Although in this case I would expect that an error pops up, as the file does not exist.

One thing which you could try is to run simulations with `run_swat` just for a short time period (exceeding of course the warm up period) and set the input argument `keep_folder = TRUE`. Then there should be a folder .model_run/thread_1 in your SWAT project folder. After the simulation is finished you could see in this folder which files were written in the simulation run. If the output files you want to return are empty then there is either something wrong with the executable or some specific settings your custom version requires and which SWATrunR does not consider.

**Comment by jmule88** [comment]
Hi Chris,

Thanks so much! This is very helpful. `keep_folder = TRUE` showed me that the parameters are successfully changing and so are the outputs. 

We are still using the generic output files, but we've added new columns that we are trying to calibrate to and modified the names/equations for existing columns. Maybe that's it.

Thanks for your help!
Jaya

**Comment by chrisschuerz** [comment]
Great! So if it is just a matter of new columns in the existing files you should be able to return the respective columns, if you use the correct names for the variables in `define_output()`.

**Comment by jmule88** [comment]
Hi Chris,

Thank you so much for your help with this! I can now see that I am successfully getting outputs for the desired column in .hru. 

However, 'Simulation' is not being populated and I'm trying to figure out why. Within the error_report table, I see that I'm getting the runtime error:

`"Note: The following floating-point exceptions are signalling: IEEE_UNDERFLOW_FLAG IEEE_DENORMAL"`

Could this be why my 'Simulation' table is not being populated? This is an error I'd like to ignore. If this error is the reason 'Simulation' isn't being populated, is it possible to override this error and populate the 'Simulation' table anyway?

Really appreciate your time!
